version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  generate_dataset:
    run: >
      ehrql:v1 generate-dataset dataset_definition_solution.py
      --output output/diabetes_dataset.csv
    outputs:
      highly_sensitive:
        measure: output/diabetes_dataset.csv
  
  create_histogram:
    run: r:latest create_histogram.R
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        histogram: output/histogram_age.png